### ISSUE TITLE
Cyclic Building scepter (fill) crashes server

### ISSUE THREAD

**Issue by Freak1091** [AllTheMods/SLOP-slice-of-pie#1]
When attempting to use a cyclic scepter of filling on waterlogged smooth stone slab (top), server crashes.

Below please find server console log of event:

14.05 01:32:23 [Server] INFO [m[1;31m[21:32:23] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: net.minecraft.block.Block.func_200291_n()Lnet/minecraft/util/text/ITextComponent;
14.05 01:32:23 [Server] INFO Index: 4
14.05 01:32:23 [Server] INFO Listeners:
14.05 01:32:23 [Server] INFO 0: NORMAL
14.05 01:32:23 [Server] INFO 1: net.minecraftforge.eventbus.EventBus$$Lambda$2519/203874793@2b0df5a0
14.05 01:32:23 [Server] INFO 2: ASM: class com.exidex.swingthroughgrass.LeftClickEventHandler onLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
14.05 01:32:23 [Server] INFO 3: net.minecraftforge.eventbus.EventBus$$Lambda$2519/203874793@4b07dfc3
14.05 01:32:23 [Server] INFO 4: ASM: com.lothrazar.cyclic.event.ItemEvents@5f222d6d onHit(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
14.05 01:32:23 [Server] INFO 5: ASM: class com.stal111.forbidden_arcanus.event.PlayerInteractListener onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
14.05 01:32:23 [Server] INFO java.lang.NoSuchMethodError: net.minecraft.block.Block.func_200291_n()Lnet/minecraft/util/text/ITextComponent;
14.05 01:32:23 [Server] INFO at com.lothrazar.cyclic.event.ItemEvents.onHit(ItemEvents.java:85)
14.05 01:32:23 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler_468_ItemEvents_onHit_LeftClickBlock.invoke(.dynamic)
14.05 01:32:23 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
14.05 01:32:23 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
14.05 01:32:23 [Server] INFO at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:778)
14.05 01:32:23 [Server] INFO at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:120)
14.05 01:32:23 [Server] INFO at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:833)
14.05 01:32:23 [Server] INFO at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40)
14.05 01:32:23 [Server] INFO at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10)
14.05 01:32:23 [Server] INFO at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
14.05 01:32:23 [Server] INFO at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
14.05 01:32:23 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
14.05 01:32:23 [Server] INFO at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
14.05 01:32:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731)
14.05 01:32:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141)
14.05 01:32:23 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
14.05 01:32:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714)
14.05 01:32:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708)
14.05 01:32:23 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
14.05 01:32:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694)
14.05 01:32:23 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641)
14.05 01:32:23 [Server] INFO at java.lang.Thread.run(Thread.java:748)
14.05 01:32:23 [Server] INFO [m[1;31m[21:32:23] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
14.05 01:32:23 [Server] INFO java.lang.NoSuchMethodError: net.minecraft.block.Block.func_200291_n()Lnet/minecraft/util/text/ITextComponent;
14.05 01:32:23 [Server] INFO at com.lothrazar.cyclic.event.ItemEvents.onHit(ItemEvents.java:85) ~[?:1.15.2-0.3.2] {re:classloading}
14.05 01:32:23 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler_468_ItemEvents_onHit_LeftClickBlock.invoke(.dynamic) ~[?:?] {}
14.05 01:32:23 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
14.05 01:32:23 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
14.05 01:32:23 [Server] INFO at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:778) ~[?:?] {re:classloading}
14.05 01:32:23 [Server] INFO at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:120) ~[?:?] {re:classloading}
14.05 01:32:23 [Server] INFO at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:833) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer}
14.05 01:32:23 [Server] INFO at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?] {re:classloading}
14.05 01:32:23 [Server] INFO at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
14.05 01:32:23 [Server] INFO at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
14.05 01:32:23 [Server] INFO at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
14.05 01:32:23 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
14.05 01:32:23 [Server] INFO at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
14.05 01:32:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
14.05 01:32:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
14.05 01:32:23 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
14.05 01:32:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
14.05 01:32:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
14.05 01:32:23 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
14.05 01:32:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
14.05 01:32:23 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
14.05 01:32:23 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211] {}
14.05 01:32:23 [Server] INFO [m[1;31m[21:32:23] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /./crash-reports/crash-2020-05-13_21.32.23-server.txt
14.05 01:32:23 [Server] INFO [m[32m[21:32:23] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
14.05 01:32:23 [Server] INFO [m[32m[21:32:23] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
14.05 01:32:23 [Disconnect] User [m[32m[21:32:23] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: Freakus has disconnected, reason: Server closed
14.05 01:32:23 [Server] INFO [m[32m[21:32:23] [Server thread/INFO] [minecraft/DedicatedServer]: Freakus left the game
14.05 01:32:23 [Server] INFO [m[32m[21:32:23] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
14.05 01:32:23 [Server] INFO [m[32m[21:32:23] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'world'/minecraft:overworld
14.05 01:32:23 [Server] INFO [m[32m[21:32:23] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (world): All chunks are saved
14.05 01:32:23 [Server] INFO [m[32m[21:32:23] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (world): All chunks are saved
14.05 01:32:23 [Server] INFO [m
14.05 01:32:23 [Multicraft] Server shut down (running)
14.05 01:32:23 [Multicraft] Restarting crashed server in 10 seconds
14.05 01:32:23 [Multicraft] Server stopped

**Comment by MadWomen** [comment]
i'm looking into it but haven't been able to replicate the issue yet.

**Comment by Freak1091** [comment]
Seems to affect other scepters, had another crash when using the exchanging scepter.
[crash-2020-05-22_23.44.14-server.txt](https://github.com/AllTheMods/SLOP-slice-of-pie/files/4671096/crash-2020-05-22_23.44.14-server.txt)

**Comment by Freak1091** [comment]
Another crash report for pick block function, this time on a different block.
[crash-2020-05-23_00.34.41-server.txt](https://github.com/AllTheMods/SLOP-slice-of-pie/files/4671144/crash-2020-05-23_00.34.41-server.txt)

**Comment by MadWomen** [comment]
in light of further bugs and crashes with cyclic, i've decided to remove the mod all together, some of its functionality are still there in other mods like industrial foregoing and mekanism for example.
