### ISSUE TITLE
Server crashing on member login due to Advancement issue

### ISSUE THREAD

**Issue by Freak1091** [AllTheMods/SLOP-slice-of-pie#2]
Upon login on my SLOP server by my one member Apyllos, the server gets overflown with advancement lines. It seems that one line in particular is the recurring one that forces a java overflow (PlayerAdvancements.func_192742_b).

Attached please find the crash report that have occurred while testing with this said member, along with a copy of their player data and advancement files. If you need anything else, please let me know.

This crash occurs even if the member is the only person logged in on the server, and even when player data has been removed prior to logging in.

This crash does NOT occur when player advancement data has been wiped.
[Advancements.zip](https://github.com/AllTheMods/SLOP-slice-of-pie/files/4738629/Advancements.zip)
[Player Data.zip](https://github.com/AllTheMods/SLOP-slice-of-pie/files/4738630/Player.Data.zip)
[crash-2020-06-05_17.13.43-server.txt](https://github.com/AllTheMods/SLOP-slice-of-pie/files/4738633/crash-2020-06-05_17.13.43-server.txt)
[crash-2020-06-05_16.30.56-server.txt](https://github.com/AllTheMods/SLOP-slice-of-pie/files/4738634/crash-2020-06-05_16.30.56-server.txt)
[crash-2020-06-05_16.58.53-server.txt](https://github.com/AllTheMods/SLOP-slice-of-pie/files/4738635/crash-2020-06-05_16.58.53-server.txt)
[crash-2020-06-05_16.59.52-server.txt](https://github.com/AllTheMods/SLOP-slice-of-pie/files/4738636/crash-2020-06-05_16.59.52-server.txt)
[crash-2020-06-05_17.04.19-server.txt](https://github.com/AllTheMods/SLOP-slice-of-pie/files/4738637/crash-2020-06-05_17.04.19-server.txt)

**Comment by MadWomen** [comment]
this should be fixed now that the pack has been cleaned up, the possible cause, the better advancement mod has been removed and most of its features have been taken over by quark.
